### ISSUE TITLE
zsh: no matches found

### ISSUE THREAD

**Issue by akarazhev** [Hardziyevich/application#10]
Hi

if I create a capacitor:

~ % curl -X POST http://localhost:8081/capacitor/create -H 'Content-Type: application/json' -d '{"value":115,"unit":"pF","voltage":"25V","case":"0402","temp-low":"-55°C","temp-high":"+125°C"}'
{"id":7}%

then I try to search it:

~ % curl -X GET http://localhost:8081/capacitor/search?id=7
zsh: no matches found: http://localhost:8081/capacitor/search?id=7

**Comment by akarazhev** [comment]
curl -X DELETE http://localhost:8081/capacitor/delete?id=1
zsh: no matches found: http://localhost:8081/capacitor/delete?id=1

**Comment by akarazhev** [comment]
~ % curl -X GET http://localhost:8081/resistor/search?value=10&unit=kOhm
[1] 1518
zsh: no matches found: http://localhost:8081/resistor/search?value=10 ~ %
[1]  + exit 1     curl -X GET http://localhost:8081/resistor/search?value=10

**Comment by akarazhev** [comment]
~ % curl -X POST http://localhost:8081/resistor/create -H 'Content-Type: application/json' -d '{"value":15,"unit":"kOhm","power":"0.1W","case":"0402","temp-low":"-55°C","temp-high":"+125°C"}'
{"id":6}%
~ % curl -X DELETE http://localhost:8081/resistor/delete?id=6
zsh: no matches found: http://localhost:8081/resistor/delete?id=6

**Comment by Hardziyevich** [comment]
Done
