### ISSUE TITLE
No matches found

### ISSUE THREAD

**Issue by akarazhev** [Hardziyevich/application#8]
Hi,

when I try to create a resistor, it seems it's OK:

`% curl -X POST http://localhost:8081/resistor/create -H 'Content-Type: application/json' -d '{"value":15,"unit":"pF","voltage":"25V","case":"0402","temp-low":"-55°C","temp-high":"+125°C"}'`

But when I try to search it, the "No matches found" appears: 

`% curl -X GET http://localhost:8081/capacitor/search?case=0402
zsh: no matches found: http://localhost:8081/capacitor/search?case=0402`

BR, Andrey K.

**Comment by Hardziyevich** [comment]
It happened because You tried to create a resistor with properties from the capacitor and after looking for that resistor in capacitors.
