### ISSUE TITLE
Update curl examples

### ISSUE THREAD

**Issue by akarazhev** [Hardziyevich/application#9]
Hi,

Update curl examples, to have them sorted, i.e. create, search, update, search, delete, search.

Propose, please, the same identifiers, i.e. :

`curl -X GET http://localhost:8081/capacitor/search?case=0603`

`Create: curl -X POST http://localhost:8081/resistor/create -H 'Content-Type: application/json' -d '{"value":15,"unit":"pF","voltage":"25V","case":"0402","temp-low":"-55°C","temp-high":"+125°C"}'`

I suppose to create a case `0402`, but the search proposes me a case which doesn't exist or another one...

BR, Andrey K.

**Comment by Hardziyevich** [comment]
I got it, I made mistake with the curl example in the README file. I will change that.
